name: Auto-merge minor/patch
on:
  workflow_dispatch:
  # schedule:
    # - cron: "0 * * * *"
jobs:
  auto-merge:
    name: Auto-merge minor and patch updates
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: koj-co/dependabot-pr-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-minor: true
          merge-patch: true
